### PR TITLE
chore: calculated features quickstart [SD-61]

### PR DESCRIPTION
**Pull request by jfsantos-ds**
Notebook providing a quickstart on calculated features.

### CODE REVIEW

**Comment by fabclmnt** [comment]
@jfsantos-ds already provided you this feedback. The graphics are not aligned with what we have in the platform. 

You have examples from the simulators, from the report pdf and in pandas-profiling. Can we at least have the graphics aligned so we can close this PR?

**Comment by fabclmnt** [comment]
@jfsantos-ds please follow the style guidelines we have at the main package. Already mentioned this in the past, and fro mthe titles and labels sizes used here something is missing.
You can fins the guidelines styles here: ydata/report/style_guide.py

If I'm not mistaken this is no longer required. Also, this is not a good practice as you're creating a new column and changing the values assigned of an existing one. Please avoid changing and showing to change Metadata columns. 
metadata.columns.update({c: Column(c, DataType.NUMERICAL, VariableType.FLOAT) for c in real_ds.columns if c != 'term'})

**Comment by jfsantos-ds** [comment]
Graphical changes implemented including importing directly the hexcodes found in report package. Label and title sizes were also changed accordingly.

Relative to your second point, from your text it seems that you expected correct data type inferrence? As of 1.26 version 2 columns need to be manually set to numerical data types, hence the metadata overwrite. I changed the previous fix to the new for loop with direct setting of the datatype attribute on the required columns.

Example is rerunning, will commit the changes tomorrow morning.

**Comment by fabclmnt** [comment]
> Graphical changes implemented including importing directly the hexcodes found in report package. Label and title sizes were also changed accordingly.
> 
> Relative to your second point, from your text it seems that you expected correct data type inferrence? As of 1.26 version 2 columns need to be manually set to numerical data types, hence the metadata overwrite. I changed the previous fix to a for loop with direct setting of the datatype attribute on the required columns.
> 
> Example is rerunning, will commit the changes tomorrow morning.

Humm not sure if you that was my point. I shared 2 notes with you:
- Given the ydata-utils package was updated, the capability of inferring the correct data types was improved and for that reason you probably don't need that line of code anymore. 
- Second - given the metadata is something inferred from the dataset, it is not a good practice to demo to customers that they can use an internal property such as columns to create new one's for the metadata. This can lead to several problems. This will be blocked in a future iterations of the package.
So the type of code to be used to changed the data types would be preferably something like selecting the column how of the metadata and only change its data type. 

Let me know if this is clear. If not, please ping me on slack for a quick discussion.

**Comment by fabclmnt** [comment]
@jfsantos-ds  I think we can proceed with the merge for this one. Please confirm with @gmartinsribeiro

**Review by gmartinsribeiro — APPROVED** [review]
looks good to me :)

**Pull request merged**
