### PR TITLE
feat: augmentation capacities pipeline

### PR DESCRIPTION
**Pull request by ubabe53**
You can access the pipeline in my workspace (dev). The lab is : insurance_augmentation.

### CODE REVIEW

**Comment by gmartinsribeiro** [comment]
@ubabe53  Where can I test this?

**Comment by fabclmnt** [comment]
@ubabe53 always include Arunn to review this type of materials as discussed.

**Comment by fabclmnt** [comment]
@ubabe53 this is an academy repo, so it's important that whenever someone runs one of the examples have at least some sort of summary and detail the use case that is being covered. I don't see that anywhere here. 

Also, the first step is always the same, add a new template notebook so users can reuse for other use cases with the following possibilites:
- Widgets to select between the different type of connectors at YData (dropdown)
- Enable the user to select the connector (AureBlob, GCS?, etc.)
- Set path as an environment variable or as an inout asked to the user.

Add this template notebook to the academy repos under a folder called _template_.

**Review by fabclmnt — CHANGES_REQUESTED** [review]
Missing use case overview:
- What is the objective of the use case (generically explain balancing and augmentation use cases)
- Brief detail an explanation on the dataset you're using -> leverage metadata information retrieved for example

New materials:
- Add new template notebook to read data.

**Comment by dr-ydata** [comment]
@ubabe53 Is this one somehow blocked on me? I just now noticed I'm here as a PR reviewer (previously I didn't have proper GitHub notifications set up, my bad).

**Comment by ubabe53** [comment]
Nope it is not, you gave me the feedbacks on the jira, I updated it. 
I only need to understand if it is okay the way we download the data, you told me could create a lot of traffic, waiting an answer from Fabiana

**Pull request closed without merging**
