### PR TITLE
feat: add privacy layer example

### PR DESCRIPTION
**Pull request by ricardodcpereira**
Please find attached a PDF with the rendered output of the notebook.
[privacy_layer.pdf](https://github.com/ydataai/academy/files/10991040/privacy_layer.pdf)

### CODE REVIEW

**Review by fabclmnt — CHANGES_REQUESTED** [review]
> Please find attached a PDF with the rendered output of the notebook. [privacy_layer.pdf](https://github.com/ydataai/academy/files/10991040/privacy_layer.pdf)

Title & notebook description shall come first (before imports)

Change the name to "YData Synthetic Data generation privacy controls". 

Avoid the use of composed functions with YData main objects. We need the users to feel comfortable with them, so they need to be clearly exposed -> Delete function _train_and_sample_from_synthesizer_ and _get_report_metrics_

Because of the above function I almost missed the point of the notebook, to learn more about the RegularSynth input parameter privacy level.

**Comment by fabclmnt** [comment]
Please move this example to the Synthesizer folder. This is not from the quality module from ydata package. 

The academy is structured in:
- ydata package modules (show case) or
- Use cases

This is to demo a capability/input parameter from the module Synthesizer, for that reason shall be under that folder.

**Comment by ricardodcpereira** [comment]
The requested changes have been applied.
Please find attached a PDF with the rendered output of the updated notebook.
[privacy_layer.pdf](https://github.com/ydataai/academy/files/11199301/privacy_layer.pdf)

**Review by fabclmnt — APPROVED** [review]
🚀

**Pull request merged**
